# Change of basis

The following note is summarized from the following videos:
* https://www.youtube.com/watch?v=HZa1RwFHgwU

Changing of basis is a way to translate a vector from one basis to another basis. This concept allow us to construct a matrix transformation and transform vectors into another vector space. 

Let's say that we have a basis A, 

$$ A =  \begin{bmatrix}
1 & 0\\
0 & 1
\end{bmatrix}$$

and a basis B,

$$ B =  \begin{bmatrix}
1 & 3\\
2 & 1
\end{bmatrix}$$

and then, consider a vector x,

$$ x =  \begin{bmatrix}
1\\
2
\end{bmatrix}$$

if we are living in world A and move in x direction, we'll end up standing at coordinate $\begin{bmatrix} 1\\ 2 \end{bmatrix}$. However, if we are at B world, moving in the x direction will make us arrive at coordinate $\begin{bmatrix} 7\\ 4 \end{bmatrix}$.

In [1]:
import numpy as np
x = [1,2]
A = [[1,0],
    [0,1]]
B = [[1,3],
    [2,1]]

np.dot(A,x), np.dot(B,x)

(array([1, 2]), array([7, 4]))

How about if we are fixing our final coordinate, let's say $ z = \begin{bmatrix} 4\\ 3 \end{bmatrix}$. To arrive at coordinate z, at A world, we need to move 4 units in the $ \begin{bmatrix} 1\\ 0 \end{bmatrix}$ direction and 3 units in the $ \begin{bmatrix} 0\\ 1 \end{bmatrix}$ direction. At world B, we'll need to move only 1 unit in the $ \begin{bmatrix} 1\\ 2 \end{bmatrix}$ and 1 unit in the $ \begin{bmatrix} 3\\ 1 \end{bmatrix}$ direction

In [3]:
z = [4, 3]
np.linalg.solve(A,z), np.linalg.solve(B,z)

(array([4., 3.]), array([1., 1.]))

What we can see here is that there is a relation between these two spaces A & B. We can connect these 2 worlds because it have the same characteristic which is, both of them are basis. The basis can be reduced into Identity matrix, which means that we can find it's inverse!

Let A & B are the 2x2 basis and
$$ Ax = y , Bz = y$$
This means that 
$$ Ax = Bz $$
Since a basis have inverse, we can relate our basis from one another by
$$ B^{-1}Ax = z $$
if we want to know z, and
$$ x = A^{-1}Bz $$ if we want to know x.

In [9]:
# 1. Given the vector [5,4], write this vector in terms of the basis:
# u1 = [2,-1] , u2 = [1,4]
U = [[2,1],
    [-1,4]]
v = [5,4]

np.linalg.solve(U,v) 

#i.e, need to move 1.7 units in u1 direction and 
# 1.4 units in u2 direction

array([1.77777778, 1.44444444])

In [10]:
# 2. Given that we have 2 basis A & B as in our introduction:
# i. What transformation should all coordinates in B undergo to get into vector space A?
# ii. What transformation should all coordinates in A undergo to get into vector space B?

A = [[1,0],
    [0,1]]
B = [[1,3],
    [2,1]]

np.dot(np.linalg.inv(A),B), np.dot(np.linalg.inv(B),A)

(array([[1., 3.],
        [2., 1.]]),
 array([[-0.2,  0.6],
        [ 0.4, -0.2]]))