# Matrix Operation
This note is a platform for me to practice on matrices operations, how to use matrices in python and how to use matrices in calculating advance mathematics problem such as in the time series, differential equation, statistics and machine learning.

Readings and data for these note can be taken from the link below:
* https://ecampusontario.pressbooks.pub/linearalgebrautm/
* https://mathworld.wolfram.com/Determinant.html#:~:text=Determinants%20are%20mathematical%20objects%20that,%2C%20the%20matrix%20is%20nonsingular).

In [24]:
# We'll build our own linear algebra package here:

import numpy as np

class mygebra:
    def __init__(self):
        pass
    
    def checkDimSum (self, mat_A, mat_B):
        if mat_A.shape != mat_B.shape:
            raise ValueError("Arrays must have the same size")
        else:
            return 1
   
    # Matrix Sum
    def oSum (self, mat_A, mat_B):
        mat_A, mat_B = np.array(mat_A), np.array(mat_B)
        if self.checkDimSum(mat_A, mat_B)==1:
            res = np.zeros(mat_A.shape)
            for i in range(res.shape[0]):
                for j in range(res.shape[1]):
                    res[i][j] = mat_A[i][j] + mat_B[i][j]
            return res
 
    def checkDimProd (self, mat_A, mat_B):
        if mat_A.shape[1] != mat_B.shape[1]:
            raise ValueError("COL first arr different from ROW second arr")
        else:
            return 1
    
    # Matrix Dot Product
    def oDot (self, mat_A, mat_B):
        mat_A, mat_B = np.array(mat_A), np.array(mat_B).T
        if self.checkDimProd(mat_A, mat_B)==1:
            res = np.zeros((mat_A.shape[0], mat_B.shape[0]))
            for i in range(res.shape[0]):
                for j in range(res.shape[1]):
                    res[i][j] = np.sum(mat_A[i]*mat_B[j])
            return res 
    
    # minor expansion
    def minor(self, mat_A):
        k = mat_A.shape[0]
        while k != 2:
            
    # nxn Matrix Determinant
    def oDet(self, mat_A):
        mat_A = np.array(mat_A)
        if mat_A.shape[0] != mat_A.shape[1]:
            raise ValueError("arr shape is not NxN")
        else:
            k = mat_A.shape[0]
            sign_A = self.oSign(k) * mat_A
            
            
    def oSign(self,k):
        mat = np.zeros((k,k))
        for i in range(k):
            for j in range(k):
                mat[i][j] = (-1)**(i+j)
        return mat

In [36]:
MO = mygebra()
A = [[2,1,3],
    [-1,2,0]]
B = [[1,1,-1],
    [2,0,6]]

#Sum Operation
MO.oSum(A,B)

array([[3., 2., 2.],
       [1., 2., 6.]])

In [28]:
A = [[2,3,5],
    [1,4,7],
    [0,1,8]]

B = [[8,9],
    [7,2],
    [6,1]]

#Dot Product Operation
MO.oDot(A,B)

array([[67., 29.],
       [78., 24.],
       [55., 10.]])

In [32]:
A = [[3,-1,2],
    [0,1,4]]

B = [[2,1,6,0],
    [0,2,3,4],
    [-1,0,5,8]]

#Dot Product Operation
MO.oDot(A,B)

array([[ 4.,  1., 25., 12.],
       [-4.,  2., 23., 36.]])

The matrix follows the following laws:
1. Associative, (AB)C = A(BC)
2. Distributive, A(B + C) = AB + AC = (B + C)A
3. Commutative only if ~
    if and only if (A - B)(A + B) = A$^{2}$ - B$^{2}$