# Matrix Operations
This note is a platform for me to practice on matrices operations, how to use matrices in python and how to use matrices in calculating advance mathematics problem such as in the time series, differential equation, statistics and machine learning.

Readings and data for these note can be taken from the link below:
* https://ecampusontario.pressbooks.pub/linearalgebrautm/
* https://mathworld.wolfram.com/Determinant.html#:~:text=Determinants%20are%20mathematical%20objects%20that,%2C%20the%20matrix%20is%20nonsingular).

In [1]:
# We'll build our own linear algebra package here:
import numpy as np

class mygebra:
    def __init__(self):
        pass
    
    def checkDimSum (self, mat_A, mat_B):
        if mat_A.shape != mat_B.shape:
            raise ValueError("Arrays must have the same size")
        else:
            return 1
   
    # Matrix Sum
    def oSum (self, mat_A, mat_B):
        mat_A, mat_B = np.array(mat_A), np.array(mat_B)
        if self.checkDimSum(mat_A, mat_B)==1:
            res = np.zeros(mat_A.shape)
            for i in range(res.shape[0]):
                for j in range(res.shape[1]):
                    res[i][j] = mat_A[i][j] + mat_B[i][j]
            return res
 
    # Matrix Transpose
    def oT (self, mat_A):
        mat_A = np.array(mat_A)
        res = np.zeros((mat_A.shape[1], mat_A.shape[0]))
        for i in range(res.shape[0]):
            for j in range(res.shape[1]):
                if i==j:
                    res[i][j] = mat_A[i][j]
                else:
                    res[i][j] = mat_A[j][i]
        return res
        
    def checkDimProd (self, mat_A, mat_B):
        if mat_A.shape[1] != mat_B.shape[1]:
            raise ValueError("COL first arr different from ROW second arr")
        else:
            return 1
    
    # Matrix Dot Product
    def oDot (self, mat_A, mat_B):
        mat_A, mat_B = np.array(mat_A), self.oT(np.array(mat_B))
        if self.checkDimProd(mat_A, mat_B)==1:
            res = np.zeros((mat_A.shape[0], mat_B.shape[0]))
            for i in range(res.shape[0]):
                for j in range(res.shape[1]):
                    res[i][j] = np.sum(mat_A[i]*mat_B[j])
            return res 
      
    # nxn Matrix Determinant
    def oDet(self, A, total=0.0):
        indices = list(range(len(A)))
     
        if len(A) == 2 and len(A[0]) == 2:
            val = A[0][0] * A[1][1] - A[1][0] * A[0][1]
            return val
 
        for fc in indices: 
            As = A # make a copy
            As = As[1:] 
            height = len(As)
            for i in range(height): 
                As[i] = As[i][0:fc] + As[i][fc+1:] 
            sign = (-1) ** (fc % 2) 
            sub_det = self.oDet(As)
            total += sign * A[0][fc] * sub_det 
        return total

    # Adjoint of a Matrix
    def oAdj(self, A):
        A = np.array(A)
        res = np.zeros(A.shape)
        if A.shape[0] == 2:
            return np.array([[-A[0][0],A[1][0]],[A[0][1],-A[1][1]]])
        else:
            for row in range(A.shape[0]): 
                for col in range(A.shape[1]):
                    sub_A = np.delete(A, row, 0)
                    sub_A = np.delete(sub_A, col, 1)
                    res[row][col] += ((-1)**(row+col)) * self.oDet(sub_A.tolist())
            return res
        
    # Inverse of Matrices
    def oInv(self, A):
        det = self.oDet(A)
        A_adj = self.oAdj(A)
        return (1/det)*A_adj

In [2]:
MO = mygebra()
A = [[2,1,3],
    [-1,2,0]]
B = [[1,1,-1],
    [2,0,6]]

#Sum Operation
MO.oSum(A,B)

array([[3., 2., 2.],
       [1., 2., 6.]])

In [3]:
MO.oT(A)

array([[ 2., -1.],
       [ 1.,  2.],
       [ 3.,  0.]])

In [4]:
A = [[2,3,5],
    [1,4,7],
    [0,1,8]]

B = [[8,9],
    [7,2],
    [6,1]]

#Dot Product Operation
MO.oDot(A,B)

array([[67., 29.],
       [78., 24.],
       [55., 10.]])

In [5]:
A = [[3,-1,2],
    [0,1,4]]

B = [[2,1,6,0],
    [0,2,3,4],
    [-1,0,5,8]]

#Dot Product Operation
MO.oDot(A,B)

array([[ 4.,  1., 25., 12.],
       [-4.,  2., 23., 36.]])

In [6]:
A = [[1,2,3,4],
     [8,5,6,7],
     [9,12,10,11],
     [13,14,16,15]]

MO.oDet(A), np.linalg.det(A)

(-348.0, -347.9999999999998)

In [7]:
MO = mygebra()
B = [[1,1,1,-1],
    [1,1,-1,1],
    [1,-1,1,1],
    [-1,1,1,1]]
MO.oAdj(B), MO.oInv(B)

(array([[-4., -4., -4.,  4.],
        [-4., -4.,  4., -4.],
        [-4.,  4., -4., -4.],
        [ 4., -4., -4., -4.]]),
 array([[ 0.25,  0.25,  0.25, -0.25],
        [ 0.25,  0.25, -0.25,  0.25],
        [ 0.25, -0.25,  0.25,  0.25],
        [-0.25,  0.25,  0.25,  0.25]]))

The matrix follows the following properties:
1. Associative, (AB)C = A(BC)
2. Distributive, A(B + C) = AB + AC = (B + C)A
3. Commutative only if ~
    if and only if (A - B)(A + B) = A$^{2}$ - B$^{2}$