# Pseudoinverse
Pseudoinverse is very useful when we had a rectangular matrix and need to find it's inverse. Usually in regression, we will always have more equation than variable. Hence, resulting us to get an overdetermined system (system with many solution or no solution). 

To get a pseudoinverse of a matrix, the Singular Value Decomposition (SVD) will be used. 

$$ A = UE V^{T}$$

using this matrix decomposition, the following step will then be used.

$$ Ax = b$$
$$ UE V^{T}x = b$$
$$ VE^{-1}U^{T}UE V^{T}x = VE^{-1}U^{T}b$$
$$ x = VE^{-1}U^{T}b$$

The $VE^{-1}U^{T}$ is our pseudoinverse because it will brings back b vector to x.

In [1]:
import numpy as np

def pseudoinv(A):
    U, S, Vt = SVD_decompose(A)
    
    S_inv = np.zeros(S.shape)
    for i in range(S.shape[0]):
        for j in range(S.shape[1]):
            if i == j:
                S_inv[i][j] = 1/S[i][j]
    S_inv = S_inv.T
    
    return np.dot(np.dot(Vt.T,S_inv),U.T)

def SVD_decompose(A):
    A = np.array(A)
    U,s,Vt = np.linalg.svd(A)
    
    S = np.zeros((len(U),len(Vt)))
    
    for i in range(len(U)):
        for j in range(len(Vt)):
            if i==j:
                S[i][j] = s[i]
                
    return U, S, Vt

In [2]:
A = [[4,0],
    [3,-5]]
pseudoinv(A)

array([[ 2.50000000e-01, -1.38777878e-17],
       [ 1.50000000e-01, -2.00000000e-01]])

In [3]:
#checking pseudoinverse

b = np.dot(A,np.array([3,1]))
b

array([12,  4])

In [4]:
np.dot(pseudoinv(A),b)

array([3., 1.])