# QR decomposition

QR decomposition or QR factorization is known as a basis for eigenvalue algorithm to calculate the eigenvalues and eigenvectors of a matrix numerically. If you have encounter with problem that requires to do eigenvalue calculation, you might notice that after doing some manipulation on our matrix, we'll end up need to calculate equations to find out our unknown $\lambda$. 

This method is developed in the late of 1950s and the idea behind the decomposition is to write the matrix as a product of an orthogonal matrix and an upper triangular matrix which is 

$$ A = QR $$

where A = a square matrix,
Q = an orthonormal matrix,
R = an upper triangular matrix.

The following note is summarized from the link below:
* https://www.youtube.com/watch?v=FAnNBw7d0vg
* https://www.youtube.com/watch?v=_neGVEBjLJA
* https://en.wikipedia.org/wiki/QR_decomposition

In [1]:
# We'll use the Gram Schmidt Process to find our QR decompose.
# for this process, we need to handle with the columns of the matrix,
# thus, it is easier for us to use a transposed matrix and then 
# transpose it again to get the actual solution.

import numpy as np

def QR(matrix):
    A = np.array(matrix).T
    u1 = A[0]
    U = np.zeros(A.shape)
    Q = np.zeros(A.shape)
    U[0] = u1
    Q[0] = A[0]/oNorm(A[0])
    
    for col in range(1,len(A)):
        proj_store = np.zeros(A.shape)
        for i in range(0, col):
            proj_store[i] = oProj(A[col],U[i])

        U[col] = A[col] - np.sum(proj_store, axis=0)
        Q[col] = U[col]/oNorm(U[col])
    
    return Q.T, np.dot(Q,A.T)

def oProj(vec1, vec2):
    # will return the projection of v1 onto v2
    v1, v2 = np.array(vec1), np.array(vec2)
    v2_norm = oNorm(v2)
    return (np.dot(v1,v2)/np.dot(v2,v2))*v2

def oNorm(vec):
    # will return the magnitude of the vector
    return np.sqrt(sum(vec**2))

In [2]:
A = [[12, -51, 4],
    [6, 167, -68],
    [-4, 24, -41]]
QR(A) 

# should obtain
# Q = [[6/7, -69/175, -58/175],    R = [[14, 21, -14],
#      [3/7, 158/175, 6/175],           [0, 175, -70],
#      [-2/7, 6/35, -33/35]]            [0,  0,  35]]

(array([[ 0.85714286, -0.39428571, -0.33142857],
        [ 0.42857143,  0.90285714,  0.03428571],
        [-0.28571429,  0.17142857, -0.94285714]]),
 array([[ 1.40000000e+01,  2.10000000e+01, -1.40000000e+01],
        [-6.66133815e-16,  1.75000000e+02, -7.00000000e+01],
        [ 0.00000000e+00,  1.42108547e-14,  3.50000000e+01]]))

We can see how this composition can help us in finding the desired eigenvalue by using the following QR algorithm

In [3]:
# the eigenvalues are the diagonal entries of the right triangular matrix
def eigen(matrix, n=10000):
    A = np.array(matrix)
    for n in range(n):
        q, r = QR(A)
        q_inv = np.linalg.inv(q)
        A = np.dot(np.dot(q_inv,A),q)
    return A   

In [4]:
eigenval, eigenvec = np.linalg.eig([[12, -51, 4],[6, 167, -68],[-4, 24, -41]])

eigen(A), eigenval #our result is close with the numpy linear algebra package

(array([[ 1.56136684e+002,  6.22705050e+001, -8.74603501e+001],
        [ 4.64421707e-322, -3.41966750e+001,  1.58136450e+001],
        [-2.42092166e-322,  2.47032823e-323,  1.60599909e+001]]),
 array([156.13668406,  16.05999094, -34.196675  ]))