# Singular Value Decomposition

$$ A = UE V^{T}$$

U and V are eigenvectors while E is a diagonal matrix with eigenvalue entries.

V can be calculated by using $A^{T}A$ while U can be calculated by using $AA^{T}$. 

The reference is as below:
* https://web.mit.edu/be.400/www/SVD/Singular_Value_Decomposition.htm

In [1]:
import numpy as np

def SVD_decompose(A):
    A = np.array(A)
    U,s,Vt = np.linalg.svd(A)
    
    S = np.zeros((len(U),len(Vt)))
    
    for i in range(len(U)):
        for j in range(len(Vt)):
            if i==j:
                S[i][j] = s[i]
                
    return U, S, Vt
    

In [2]:
A = np.array([[2,4],
    [1,3],
    [0,0],
    [0,0]])

a, b, c, = SVD_decompose(A)
np.dot(np.dot(a,b),c), a, b, c

(array([[2., 4.],
        [1., 3.],
        [0., 0.],
        [0., 0.]]),
 array([[-0.81741556, -0.57604844,  0.        ,  0.        ],
        [-0.57604844,  0.81741556,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  1.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  1.        ]]),
 array([[5.4649857 , 0.        ],
        [0.        , 0.36596619],
        [0.        , 0.        ],
        [0.        , 0.        ]]),
 array([[-0.40455358, -0.9145143 ],
        [-0.9145143 ,  0.40455358]]))